### ISSUE TITLE
rrdtool.fetch -> Segmentation fault 

### ISSUE THREAD

**Issue by atommaki** [commx/python-rrdtool#34] opened 2020-02-06 20:51 UTC
**Describe the bug**
rrdtool.fetch with wrong argument cause segmentation fault

**To Reproduce**

This one works well:
```
rrdtool.fetch("/var/lib/munin/localdomain/localhost.localdomain-cpu-user-d.rrd", "AVERAGE")
```

but this one cause a segmentation fault:

```
rrdtool.fetch("/var/lib/munin/localdomain/localhost.localdomain-cpu-user-d.rrd", "invalid")
```

**Expected behavior**
Getting an error message instead of a segmentation fault

**Desktop (please complete the following information):**
 - Python version: 3.6.9
 - RRDtool version: 1.7.0
 - python-rrdtool version: 0.1.10

on Ubuntu 18.04

**Comment by commx** [comment] 2020-02-06 21:26
Hi,

can't reproduce that behaviour. Tested with both 0.1.10 and 0.1.15 (latest):

```
>>> rrdtool.fetch('power.rrd', 'invalid')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
rrdtool.OperationalError: unknown consolidation function 'invalid'
```

How did you install the library?

**Comment by atommaki** [comment] 2020-02-06 22:22
It is from the ubuntu repo (Ubuntu 18.04):
`apt install python3-rrdtool`

**Comment by atommaki** [comment] 2020-02-06 22:27
I thought it may be not the python package but the rrdtool itself, but that work from command line.
This gives the data:
`rrdtool fetch /var/lib/munin/localdomain/localhost.localdomain-cpu-user-d.rrd AVERAGE`

and this one gives an error:
`rrdtool fetch /var/lib/munin/localdomain/localhost.localdomain-cpu-user-d.rrd invalid
ERROR: unknown consolidation function 'invalid'
`

**Comment by atommaki** [comment] 2020-02-06 22:30
the rrdtool.fetch gives me the same segfault if I forget the 2nd parameter:

```Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rrdtool
>>> rrdtool.fetch("/var/lib/munin/localdomain/localhost.localdomain-cpu-user-d.rrd")
Segmentation fault (core dumped)
```

**Comment by atommaki** [comment] 2020-02-06 22:57
`python3 -m pip install rrdtool` solved the problem (which also updated the package from 0.1.10 to 0.1.15), now I get the ` unknown consolidation` error too (instead of the segfault). Still strange...

**Comment by commx** [comment] 2020-02-06 23:52
Identified the issue.

The bindings in this repo were never affected (and that's why the "pip" version works). Since 2017, a copy of the bindings here replaced the rrdtool python bindings in the upstream rrdtool distribution, which is used as source for Debian (and Ubuntu) packages. [This commit](https://github.com/oetiker/rrdtool-1.x/commit/411f10cb03d893a76738af4176af43665f37f791#diff-cb8fc5cdea5f797ac2974a80899f0920) moved some deallocation calls which will cause your original issue as it tries to free memory from uninitialized pointers.

I have opened a pull request on [oetiker/rrdtool-1.x](https://github.com/oetiker/rrdtool-1.x) to get the regression fixed there.

**Comment by commx** [comment] 2020-02-10 00:40
Will close this issue as its not related to this repository, but to upstream. Once the upstream PR is merged, it may take some time until the fix is included in the standard package repositories.

**Closed by commx** 2020-02-10 00:40 UTC
Labels: bug
