### ISSUE TITLE
Missing LICENSE file in PyPI distribution

### ISSUE THREAD

**Issue by lachs0r** [commx/python-rrdtool#28] opened 2019-05-12 02:38 UTC
To make this module reproducible, please include the LICENSE file in its PyPI package.

**Comment by commx** [comment] 2019-05-17 12:29
Technically not a bug, so removing the bug label.

Setuptools seems not to include the LICENSE file in the distribution archives. I've tweaked the setup script a bit to include it. Released as v0.1.15.

Thanks for reporting.

**Closed by commx** 2019-05-17 12:29 UTC
